### ISSUE TITLE
Cannot import name 'DocTypeMeta'

### ISSUE THREAD

**Issue by deft01** [sabricot/django-elasticsearch-dsl#119]
Working with python3 (3.5.3).
Last django release (2.0.7).
Last release of django_elasticsearch_dsl (cloned).

Idk what the mistake is...

```python
In [1]: import django_elasticsearch_dsl
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-43bb12786d78> in <module>()
----> 1 import django_elasticsearch_dsl

/usr/local/lib/python3.5/dist-packages/django_elasticsearch_dsl/__init__.py in <module>()
      1 from django.utils.module_loading import autodiscover_modules
      2 
----> 3 from .documents import DocType  # noqa
      4 from .indices import Index  # noqa
      5 from .fields import *  # noqa

/usr/local/lib/python3.5/dist-packages/django_elasticsearch_dsl/documents.py in <module>()
      6 from elasticsearch.helpers import bulk
      7 from elasticsearch_dsl import DocType as DSLDocType
----> 8 from elasticsearch_dsl.document import DocTypeMeta as DSLDocTypeMeta
      9 from elasticsearch_dsl.field import Field
     10 

ImportError: cannot import name 'DocTypeMeta'```

**Comment by DusanMadar** [comment]
It's because a fairly recent **breaking change** to  `elasticsearch_dsl` (http://elasticsearch-dsl.readthedocs.io/en/latest/Changelog.html#id3).

Installing the previous version works for me; `pip install elasticsearch-dsl==6.1.0`.

**Comment by deft01** [comment]
I will try this evening and give a feedback. Thx for helping !

**Comment by jaddison** [comment]
Duplicate of #115.

**Comment by safwanrahman** [comment]
Closing this as its already issued in #115

**Comment by shasha88** [comment]
Hi guys,
I am trying to connect to elasticsearch using django-elasticsearch-dsl.
But, this error keeps coming. I tried downgrading elasticsearch-dsl. but it didnot work

I am using python 3.7. do you think there is compatibility issues? 
Thanks
[error.txt](https://github.com/sabricot/django-elasticsearch-dsl/files/2513287/error.txt)
