### ISSUE TITLE
Can't get the queryset with to_queryset 

### ISSUE THREAD

**Issue by ahivert** [sabricot/django-elasticsearch-dsl#82]
- django-elasticsearch-dsl==0.4.4
- Django==1.10.7
- elasticsearch==2.3.0
- elasticsearch-dsl==2.0.0

```
s = Document.search().filter('match', name='test')[:30]
s.to_queryset()
```
Raise this error
```
AttributeError: 'Search' object has no attribute '_source'
```
`s.__dict__` return 
```
{'_doc_type': ['buyer_alias_document'],
 '_doc_type_map': {'buyer_alias_document': <bound method DocTypeMeta.from_es of <class 'jurismarches.buyers.documents.BuyerAliasDocument'>>},
 '_extra': {},
 '_fields': None,
 '_highlight': {},
 '_highlight_opts': {},
 '_index': ['buyer_alias'],
 '_model': <class 'jurismarches.buyers.models.BuyerAlias'>,
 '_params': {},
 '_partial_fields': {},
 '_post_filter_proxy': <elasticsearch_dsl.search.QueryProxy object at 0x7fb285a9c588>,
 '_query_proxy': <elasticsearch_dsl.search.QueryProxy object at 0x7fb285a9c550>,
 '_response_class': <class 'elasticsearch_dsl.result.Response'>,
 '_script_fields': {},
 '_sort': [],
 '_suggest': {},
 '_using': 'default',
 'aggs': AggsProxy()}
```

**Comment by sabricot** [comment]
Yes, it seems it is not working with `elasticsearch-dsl==2.0.0`, i will update the minimum requirement to `elasticsearch-dsl==2.1.0`.
Is it possible for you tu use `elasticsearch-dsl==2.1.0` or `elasticsearch-dsl==2.2.0` ?

**Comment by ahivert** [comment]
So fast ! 
No problem to use `elasticsearch-dsl==2.2.0` I will do that.

Thank you ! :+1:
